<?php
// statistic_report.php
// This page displays the most and least popular routes for a selected date from the 'statistic' table.

require_once '../classes/Database.php';

// Prepare DB connection
$database = new Database();
$db = $database->getConnection();

// Handle date filter
$filterDate = $_GET['stat_date'] ?? '';
$where = '';
$params = [];
if ($filterDate) {
    $where = 'WHERE s.statDate = ?';
    $params = [$filterDate];
}

// Fetch most popular
$stmt1 = $db->prepare("
    SELECT s.*, a.adminName FROM statistic s
    LEFT JOIN admin a ON s.adminID = a.adminID
    $where AND s.reportType = 'most_popular'
    ORDER BY s.statDate DESC, s.totalPassengers DESC
");
$stmt1->execute($params);
$mostPopular = $stmt1->fetchAll(PDO::FETCH_ASSOC);

// Fetch least popular
$stmt2 = $db->prepare("
    SELECT s.*, a.adminName FROM statistic s
    LEFT JOIN admin a ON s.adminID = a.adminID
    $where AND s.reportType = 'least_popular'
    ORDER BY s.statDate DESC, s.totalPassengers ASC
");
$stmt2->execute($params);
$leastPopular = $stmt2->fetchAll(PDO::FETCH_ASSOC);
?>
<!DOCTYPE html>
<html>
<head>
    <title>Statistical Reports</title>
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css' rel='stylesheet'>
</head>
<body>
<div class='container py-4'>
    <h1>Statistical Reports</h1>
    <form method="get" class="row g-3 align-items-end mb-4">
        <div class="col-auto">
            <label for="stat_date" class="form-label mb-0">Date</label>
            <input type="date" class="form-control" name="stat_date" id="stat_date" value="<?= htmlspecialchars($filterDate) ?>">
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary">Filter</button>
        </div>
    </form>
    <h3>Most Popular Route</h3>
    <table class='table table-bordered table-striped'>
        <thead>
            <tr>
                <th>Route</th>
                <th>Date</th>
                <th>Total Passengers</th>
                <th>Total Cancellations</th>
                <th>Generated By</th>
                <th>Generated At</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($mostPopular as $row): ?>
            <tr>
                <td><?= htmlspecialchars($row['route']) ?></td>
                <td><?= htmlspecialchars($row['statDate']) ?></td>
                <td><?= htmlspecialchars($row['totalPassengers']) ?></td>
                <td><?= htmlspecialchars($row['totalCancellations']) ?></td>
                <td><?= htmlspecialchars($row['adminName'] ?? 'N/A') ?></td>
                <td><?= htmlspecialchars($row['generatedAt']) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <h3>Least Popular Route</h3>
    <table class='table table-bordered table-striped'>
        <thead>
            <tr>
                <th>Route</th>
                <th>Date</th>
                <th>Total Passengers</th>
                <th>Total Cancellations</th>
                <th>Generated By</th>
                <th>Generated At</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($leastPopular as $row): ?>
            <tr>
                <td><?= htmlspecialchars($row['route']) ?></td>
                <td><?= htmlspecialchars($row['statDate']) ?></td>
                <td><?= htmlspecialchars($row['totalPassengers']) ?></td>
                <td><?= htmlspecialchars($row['totalCancellations']) ?></td>
                <td><?= htmlspecialchars($row['adminName'] ?? 'N/A') ?></td>
                <td><?= htmlspecialchars($row['generatedAt']) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <a href='admin_dashboard.php' class='btn btn-secondary'>Back to Dashboard</a>
</div>
</body>
</html>
